### ISSUE TITLE
Use `-webkit-font-smoothing`

### ISSUE THREAD

**Issue by chris-pearce** [chris-pearce/cjpearce.com#38]
```css
@media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-resolution: 2dppx)
body {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
}
```

—https://twitter.com
